name: Compile and publish resume to S3

on:
  push:
    branches: ["main"]

jobs:
  run-command:
    runs-on: texlive/texlive:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Compile resume
      run: cd resume/ && pdflatex resume.tex

    - name: Upload resume PDF as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: resume.pdf
